# Generated by Django 2.1.5 on 2020-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='ciudad',
            field=models.CharField(choices=[['Higuerote', 'Higuerote'], ['Caracas', 'Caracas'], ['Guatire', 'Guatire']], max_length=15),
        ),
    ]
