# Generated by Django 2.1.5 on 2020-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200707_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='ciudad',
            field=models.CharField(choices=[['Higuerote', 'Higuerote'], ['Caracas', 'Caracas'], ['Guarenas - Guatire', 'Guarenas - Guatire']], max_length=20),
        ),
    ]
